### ISSUE TITLE
Needs a licence / license?

### ISSUE THREAD

**Issue by mwardm** [jbubriski/Encryptamajig#10]
John,
Like the idea.  (It annoys me when Microsoft [or others] supply you with a bag of bits and no simple way to do the thing you think you want the bits for.)
I couldn't find a licence on this code though - which contrary to your stated intention, kinda stops me from using it!
Cheers,
Mike.

**Comment by jbubriski** [comment]
MIT FTW!

**Comment by mwardm** [comment]
Where's the +1  / Like / "Good man!" button on GitHub?  :-)

**Comment by jbubriski** [comment]
Star it!
